export const countries = [
  "Philippines", // Placed at the top as requested
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, Democratic Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const options = {
  civilStatus: ["Single", "Married", "Divorced", "Widowed"],
  religion: [
    "Roman Catholicism",
    "Islam",
    "Iglesia ni Cristo",
    "Seventh-day Adventist",
    "Aglipayan Church (Philippine Independent Church)",
    "Iglesia Filipina Independiente",
    "Bible Baptist Church",
    "United Church of Christ in the Philippines",
    "Jehovah's Witnesses",
    "Church of Christ",
    "Other Christian denominations",
    "Indigenous Philippine folk religions",
    "Buddhism",
    "Other religions",
    "No religion",
  ],
  gender: ["Male", "Female", "Other"],
  suffix: [
    "Jr.", // Junior
    "Sr.", // Senior
    "II", // Second
    "III", // Third
    "IV", // Fourth
    "V", // Fifth
    "MD", // Doctor of Medicine
    "PhD", // Doctor of Philosophy
    "Esq.", // Esquire (Law)
    "DDS", // Doctor of Dental Surgery
    "CPA", // Certified Public Accountant
  ],
};

export const formFields = [
  {
    id: "firstName",
    name: "firstName",
    label: "First Name",
    placeholder: "John",
  },
  {
    id: "middleName",
    name: "middleName",
    label: "Middle Name",
    placeholder: "A.",
  },
  {
    id: "lastName",
    name: "lastName",
    label: "Last Name",
    placeholder: "Doe",
  },
  {
    id: "mobileNumber",
    name: "mobileNumber",
    label: "Mobile Number",
    placeholder: "09454356673",
  },
  {
    id: "age",
    name: "age",
    label: "Age",
    type: "number",
    placeholder: "30",
  },
  {
    id: "address",
    name: "address",
    label: "Address",
    placeholder: "123 Main St",
  },

  {
    id: "work",
    name: "work",
    label: "Work",
    placeholder: "Software Engineer",
  },
  {
    id: "language",
    name: "language",
    label: "Language",
    placeholder: "English",
  },
  {
    id: "email",
    name: "email",
    label: "Email",
    type: "email",
    placeholder: "john.doe@example.com",
  },
];

export const dropDownFields = [
  {
    id: "suffix",
    name: "suffix",
    label: "Suffix",
    options: options.suffix,
  },
  {
    id: "gender",
    name: "gender",
    label: "Gender",
    options: options.gender,
  },
  {
    id: "civilStatus",
    name: "civilStatus",
    label: "Civil Status",
    options: options.civilStatus,
  },
  {
    id: "religion",
    name: "religion",
    label: "Religion",
    options: options.religion,
  },
];
